### ISSUE TITLE
Version v4/v5 items

### ISSUE THREAD

**Issue by patocallaghan** [adopted-ember-addons/ember-data-factory-guy#444]
Potential list of things to change to ship a v4

* [x] Upgrade to more modern Ember LTS & Node version #443
* [x] Add ember-try scenarios #443
* [x] Upgrade old Broccoli plugins #441 
* [x] Add release-it-lerna-changelog to the repo to align with other Adopted Ember Addons https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/454
* [x] Remove custom vendor code in place of using ember-auto-import. https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/510
  * [x] ember-auto-import v2
* [x] Fix Embroider compatibility #437 
* [x] Fix Factory Guy + Model Fragments + newer Ember Data incompatibility #417
* [x] Remove deprecated helpers: `mockSetup`, `mockTeardown` and `mockFind` https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/463
* [x] Modernize dummy app codebase to Octane
* [x] Fix deprecation warnings
* [x] Ember v4
* [x] Ember Addon V2 https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/510

**Comment by averydev** [comment]
😍

**Comment by patocallaghan** [comment]
Dummy app modernized by @Techn1x in https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/474

**Comment by Techn1x** [comment]
v4 was shipped with most of these items, v5 will have the remainder

**Comment by Techn1x** [comment]
resolved https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/506
